### ISSUE TITLE
Possible Ticket use in Vehicle

### ISSUE THREAD

**Issue by Flowrider** [xDreamLand/dr-scratching-qbcore#1]
You can use the ticket in the Vehicle and fall out.
I have not yet been able to test it myself, but I was told by a player. Maybe you can take a look at it.
Thanks

https://user-images.githubusercontent.com/6627753/154033282-1757fdf3-389b-494f-89f9-d334d1a2c0c4.mp4

https://user-images.githubusercontent.com/6627753/154033293-b084ba86-d203-4103-9cce-c0945792d9d0.mp4

**Comment by nzkfc** [comment]
Yeah we have the same issue, should be able to be fixed to use this while driving, or simply detect if in car then pop up notification syaing "you can't scratch and drive" or something as an easy fix.

**Comment by michieldesair** [comment]
Hi, issue has been fixed in 3.2.0. Thanks!
