### ISSUE TITLE
Pay more attention to your code

### ISSUE THREAD

**Issue by RealKawfee** [xDreamLand/dr-scratching-qbcore#2]
Code to copy should include quotes (") around item, not apostrophes. Literally that small detail caused me to spin circles thinking this didn't work. 

Correct text should be "item", NOT 'item'.

Pay more attention to what you're sharing. People are going nuts trying to figure out why it doesn't work.

**Comment by michieldesair** [comment]
Where do you see this? I'm not following completely.

**Comment by michieldesair** [comment]
Never heard of this issue elsewhere, no comment. Closing. Please reopen if you can give some further explanation.
