### ISSUE TITLE
OX INV SUPPORT

### ISSUE THREAD

**Issue by ItssJxstnDe** [xDreamLand/dr-scratching-qbcore#3]
Support IT!

**Comment by ItssJxstnDe** [comment]
qb-inv is shit!

**Comment by michieldesair** [comment]
Hi, it should be as simple as just replacing the exports with the OX INV exports. See > https://overextended.dev/ox_inventory/Functions/Server

There is a bunch of inventory resources. I'd like to keep it as simple as possible to customize!
